-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 27-06-2023 a las 00:52:56
-- Versión del servidor: 10.4.27-MariaDB
-- Versión de PHP: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `laravel`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_reset_tokens_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(5, '2023_06_21_230353_create_noticias_table', 2);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `noticias`
--

CREATE TABLE `noticias` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `titulo` varchar(255) NOT NULL,
  `contenido` text NOT NULL,
  `fecha_publicacion` date NOT NULL,
  `imagen` varchar(255) NOT NULL,
  `autor` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `noticias`
--

INSERT INTO `noticias` (`id`, `created_at`, `updated_at`, `titulo`, `contenido`, `fecha_publicacion`, `imagen`, `autor`) VALUES
(1, '2023-06-22 09:11:47', '2023-06-22 12:35:22', 'Cerrar el grifo: cómo el mundo puede poner fin a la contaminación por plásticos y crear una economía circular', 'La ONU, a través de su Programa para el Medio Ambiente, ha elaborado un informe que contiene una propuesta de un cambio sistémico que resuelva de raíz las causas de la contaminación por plásticos y combine: la reducción del uso problemático e innecesario del plástico con una transformación del mercado hacia la circularidad de los plásticos. Estos objetivos combinados se lograrán fomentando cambios en tres ámbitos clave: la reutilización, el reciclaje y la reorientación-diversificación, así como la adopción de medidas para hacer frente al impacto histórico de la contaminación por plásticos.\n\nLa reutilización alude a la transformación de la \'economía de usar y desechar\' hacia una \'sociedad de la reutilización\' en la que reutilizar los productos de plástico tiene más sentido económico que desecharlos. En el informe se hace hincapié en la importancia de acelerar el mercado del reciclaje de plásticos para garantizar que reciclar se convierta en un negocio económicamente más rentable.\n\nLa reorientación-diversificación alude a la transición del mercado hacia alternativas sostenibles al plástico, lo que requerirá un cambio en la demanda de los consumidores, los marcos normativos y los costes.\n\nEl informe señala que estas soluciones ya están disponibles y que un cambio integral en los sistemas y sectores pertinentes respaldado por los instrumentos normativos necesarios generará una serie de beneficios económicos y reducirá los daños a la salud humana, el medio ambiente y el clima.', '2023-06-22', 'images/grifo.jpg', 'admin'),
(2, '2023-06-22 08:44:55', '2023-06-22 08:44:55', 'La conciencia ambiental crece en España', 'El próximo lunes 5 de junio se celebra el Día Mundial del Medio Ambiente y la buena noticia es que la mayoría de los españoles estamos concienciados sobre la importancia de los valores medioambientales. No hay diferencias entre edad, sexo, nivel formativo o ideología. El interés en una escala del 1 al 10 ha pasado del 6,4 de 2005 a un 8,4 en la actualidad y la subida ha sido acentuada sobre todo en la última década.\n\nLos españoles no solo se interesan por estos temas, además reclaman más respuestas políticas ante la gravedad de la situación. Así lo refleja el estudio de la Fundación BBVA Valores, actitudes y conducta medioambiental de los españoles.\n\nOcho de cada diez es consciente de que los humanos somos la causa del calentamiento global y las conductas ecológicas como el reciclaje o la compra de electrodomésticos han calado en la amplia mayoría. Más resistencia hay con los hábitos que tienen que ver con la movilidad.\n\nProfunda preocupación, pero estamos a tiempo\n\nLa ciudadanía manifiesta una profunda preocupación por la degradación del medio ambiente, considera que la situación es grave y que existe un desajuste entre el reto a resolver y las medidas que, hasta la fecha, se han puesto en marcha para atajarlo.\n\nSegún la encuesta la mayoría de los españoles considera que los problemas derivados del medio ambiente son más graves que los que acarrea el coronavirus.', '2023-06-21', 'images/conciencia_medioambiental.jpg', 'sforjab'),
(3, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Rerum perferendis atque doloribus velit sint.', 'Quae enim architecto optio laboriosam ut. Est voluptate autem facere eos aliquid qui velit qui. Debitis eius sequi libero ipsam.\n\nQuis eius facere ratione quas quos quasi quia maiores. Aut impedit labore dolor nobis similique. Repellat commodi ullam enim repudiandae ab provident. Possimus qui suscipit et nam possimus.\n\nVoluptas illo amet repellendus eligendi aspernatur odit fugiat. Sunt quisquam consequatur labore ut eos soluta. Sapiente nihil neque fugiat aliquid minima. Beatae dolores exercitationem veritatis blanditiis non sint.', '2014-03-10', 'images/fake-image.jpg', 'Cheyenne Durgan'),
(4, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Modi nostrum consequatur aliquam vel quia.', 'Quaerat quisquam odit sit eveniet quasi. Ut ut non nam tempore adipisci expedita. Autem sint voluptatem et sunt.\n\nAssumenda aliquid voluptatem quos aut. Rem cumque blanditiis est optio rerum aut quia aut. Harum quia quo ad deserunt ab. Velit explicabo suscipit nobis blanditiis aut qui ea sit. Repellendus atque veritatis sed rerum culpa dicta.\n\nEos quam ducimus distinctio ex sunt amet expedita. Animi a exercitationem exercitationem maxime harum enim at. Molestiae quae quis nemo eligendi consequuntur. Facere ut accusamus facilis autem. Dolores odit quod fuga recusandae aperiam.', '1984-06-22', 'images/fake-image.jpg', 'Madie Ritchie Jr.'),
(5, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Neque libero dolorem nihil nam.', 'Repudiandae velit voluptatem dicta magnam atque. Ex et delectus placeat iure. Optio molestias asperiores omnis cum delectus sit. Delectus et natus rerum quo eveniet et fugiat. Ratione commodi doloribus ut qui nesciunt saepe.\n\nSapiente nisi amet est consequatur illum. Aliquam quos praesentium consectetur rerum. Ea consequatur ex beatae aut autem. At soluta voluptatibus earum labore id labore.\n\nQui aut in suscipit nihil. Eos reiciendis et eligendi. Asperiores modi quos rerum eaque voluptates et eum.', '2021-07-29', 'images/fake-image.jpg', 'Dean Volkman'),
(6, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Assumenda aut laudantium magnam tempora placeat quis libero.', 'Eligendi dolor sunt beatae aut porro. Qui non culpa officiis quia qui. Sed aut nobis consequatur qui atque aut ut suscipit. Minima porro nihil esse magni et sit.\n\nProvident aliquam consequatur facere eveniet sit atque. Est voluptas iure eius libero in. Doloribus ratione debitis reiciendis voluptatem.\n\nTemporibus quam blanditiis dolor tenetur. Et et aliquam suscipit occaecati illum cumque aut. Et minus nisi qui veritatis. Unde accusantium autem in voluptatem qui autem.', '2021-08-02', 'images/fake-image.jpg', 'Mrs. Carlotta Shields V'),
(7, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Aut qui natus est quibusdam.', 'Occaecati velit et rerum veritatis. Quos enim non magni accusamus.\n\nId ex nisi laborum sit et aut. Soluta omnis est rerum illo nesciunt qui. Tempora quia reprehenderit voluptate eveniet.\n\nQui impedit deserunt minima tenetur quia. Vitae rerum enim adipisci dolore sint earum nisi et. Quo dolor dolor ut placeat. Adipisci doloribus occaecati ab atque cupiditate ut.', '2000-09-04', 'images/fake-image.jpg', 'Ms. Earnestine Towne'),
(8, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Omnis rerum dolorem rerum eligendi eos.', 'Enim omnis iusto sit pariatur sit. Accusamus qui illum quia cumque. Voluptatem qui saepe doloremque cum ut.\n\nEsse blanditiis vero nulla ipsa perferendis in reiciendis. Quae ipsam necessitatibus maiores odit in est maxime. Accusamus dolor et soluta.\n\nSunt sunt dolor perspiciatis consectetur doloribus est rerum. Ut consequatur et ut aut. Exercitationem fugiat iste in consequuntur aut quam earum.', '2009-06-21', 'images/fake-image.jpg', 'Keara Beahan'),
(9, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Eos consequatur ipsum harum aliquam quo ea sed architecto.', 'Inventore quia qui accusamus ut architecto voluptatibus nulla. Aliquam sequi ut inventore non. Voluptas veniam nobis tempore possimus earum nesciunt. Eos voluptate ut molestias ut.\n\nConsequatur ex nisi eaque quia fugiat. Sunt sed similique ipsum odit ut. Totam quia sunt iure ut in. Minima quibusdam est atque vitae doloribus qui.\n\nSapiente placeat ut eum qui omnis cumque quos. Autem accusantium perferendis delectus fuga. Quo dolores minus maxime laboriosam laborum reiciendis. Ea molestiae dolorem in debitis quas omnis.', '2001-10-01', 'images/fake-image.jpg', 'Johanna Osinski'),
(10, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Dignissimos optio qui accusamus illo cum rem.', 'Error nihil qui quia aut ullam soluta vero quia. Velit et aut perferendis repellendus. Nesciunt vitae voluptatem rem ut.\n\nQui voluptate deserunt doloribus rerum. Maiores non officia quo accusamus.\n\nEa eos aperiam sunt aut id officia autem. Laboriosam similique cupiditate explicabo deleniti voluptatem occaecati qui. Est dolorem assumenda repudiandae vel consequatur et.', '1978-10-15', 'images/fake-image.jpg', 'Nyah Collier PhD'),
(11, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Voluptas tempora et quia vero hic eligendi veniam.', 'Non nihil enim veritatis suscipit odio provident et. Ut sint temporibus sit.\n\nMolestiae et aut molestiae soluta unde illo. Saepe earum fugit sed id possimus ullam saepe. Voluptates explicabo voluptates natus nobis et. Sint illo est qui aliquid quisquam.\n\nDoloribus porro quibusdam maiores odio nihil voluptatibus. Qui dicta eius dolorem minima dignissimos. Molestias quia officiis suscipit placeat repellat maiores ea. Odio enim consectetur eligendi debitis.', '1975-08-04', 'images/fake-image.jpg', 'Orie Grant'),
(12, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Voluptas earum excepturi quaerat repudiandae.', 'Vitae qui eligendi voluptas nulla qui laboriosam sed. Dolorum expedita pariatur molestiae et id. Ducimus et sunt distinctio quibusdam eum in nobis. Et labore quo consequuntur et.\n\nSed quia at est reprehenderit. Eum eligendi veniam facere laborum dolore quia.\n\nPraesentium laudantium aut deserunt. Aut asperiores natus qui. Ipsum facere molestiae maiores quis sapiente ut sed. Doloribus asperiores officia placeat. Veritatis saepe fugiat molestiae atque nam et quibusdam.', '1977-03-04', 'images/fake-image.jpg', 'Sean Champlin'),
(13, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Iste quo natus eaque quae laudantium molestiae.', 'Aut voluptas officiis ullam amet nemo sed consectetur. Iure expedita expedita eaque. Velit nobis dolor non doloribus.\n\nId perferendis nobis nihil alias. Vitae ipsam vel officiis quisquam accusantium rerum aspernatur. Quia ducimus ab maiores sunt. Cupiditate nesciunt explicabo sit natus quos.\n\nEos omnis delectus qui magni. Cupiditate aut vel enim. Amet sunt voluptatem velit et tenetur voluptas reiciendis. Praesentium enim occaecati quo sunt quia tenetur. Iure ea non mollitia itaque molestias sit facilis.', '2001-01-26', 'images/fake-image.jpg', 'Cale Auer'),
(14, '2023-06-22 20:32:49', '2023-06-22 20:32:49', 'Placeat necessitatibus aut maiores expedita.', 'Et maiores consequatur dolor ipsa consequatur dolore. Voluptatem eum quaerat ut molestiae odio deleniti perferendis. Architecto aperiam odio ullam.\n\nConsequuntur veniam numquam voluptate ea fugiat vitae. Fugiat voluptatem ratione maxime provident placeat iusto sed. Nisi quis qui ea excepturi voluptate. Accusantium molestias qui omnis laboriosam non.\n\nCorrupti qui assumenda exercitationem repudiandae nisi et cum. Eum dicta id sint totam repellat sequi hic eos. Eos esse tempore numquam dignissimos optio aliquam quasi ut. Maxime a quae et voluptate velit.', '2015-12-10', 'images/fake-image.jpg', 'Ms. Rahsaan Hansen'),
(15, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Eveniet earum et impedit est deserunt qui ut illo.', 'Omnis sint quaerat omnis sit perspiciatis doloremque quae eaque. Odit ipsa sint mollitia architecto. Possimus consequuntur eum consequatur cupiditate. Soluta dolore consectetur ipsam consequatur blanditiis non ex.\n\nIure in est placeat voluptatem minus dolore iusto. Adipisci nemo consectetur sit nisi minima et. Esse nulla aut vel quos corporis. Omnis neque reprehenderit a dicta consequatur odio aut.\n\nUt quo praesentium alias debitis eius quaerat. Ut dolorem nesciunt sed nostrum. Maiores delectus voluptatem temporibus vel dolor et consequatur. Dignissimos hic praesentium dicta quidem ipsa totam.', '2011-03-01', 'images/fake-image.jpg', 'Kristofer Daugherty'),
(16, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Explicabo qui est et beatae.', 'Porro sit dolorum earum saepe. Sit sint dolor ducimus placeat repellendus. Accusantium ipsum vero adipisci eveniet non. Qui laboriosam incidunt ab aut ut corporis qui.\n\nId perspiciatis quaerat molestiae ut laborum enim. Quis quos placeat mollitia occaecati. Ut laborum est dignissimos amet et et.\n\nAlias nihil iure reprehenderit adipisci rerum rerum asperiores. Voluptatum aut error aspernatur omnis. Nam earum ea soluta possimus porro.', '1987-03-10', 'images/fake-image.jpg', 'Naomi Bednar'),
(17, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Ut hic ipsa sed quo rem voluptatem.', 'Doloribus maiores placeat dolor dicta et voluptatem aperiam. Laboriosam placeat distinctio aut aperiam pariatur. Officia minus quos molestiae labore.\n\nFacilis rerum mollitia fugiat sed amet animi dicta. Vero veritatis repellendus sint quam et repellendus. Libero veniam molestiae quisquam libero provident.\n\nVoluptatem impedit nostrum ipsam voluptate et. Quis eos totam consequuntur occaecati. Doloribus non veniam ex ullam non amet.', '2018-08-07', 'images/fake-image.jpg', 'Prof. Jeffery Balistreri'),
(18, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Aliquam maxime totam quasi consequatur.', 'Beatae omnis voluptas consectetur ut. Non fugit qui commodi inventore. Nesciunt ut enim exercitationem. Est incidunt eum officiis dolorum nam. Perferendis officiis aspernatur sit minus.\n\nOfficia modi vel aut quasi et. Rerum harum earum sequi facilis temporibus id ut. Commodi architecto porro dicta consequuntur et necessitatibus delectus earum. Earum necessitatibus optio dolor voluptatum sed vero cupiditate.\n\nUt veniam corporis neque officia corporis cumque vel. Ad et accusantium dolorum aliquam rerum voluptatem qui. Nostrum necessitatibus odio nihil magni dolores necessitatibus. Quisquam deleniti sit reprehenderit et eligendi.', '1974-11-26', 'images/fake-image.jpg', 'Edgar Cremin'),
(19, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Nisi nihil voluptatibus qui accusamus et doloremque doloribus.', 'Non deserunt molestias distinctio. Nihil ex illo reprehenderit blanditiis. Rem porro est voluptatem perspiciatis.\n\nAspernatur voluptas harum doloremque ut. Iste consequatur dolorum odio in esse. Minima est consequatur eos perspiciatis explicabo.\n\nCupiditate sunt ad aut est debitis molestiae sed saepe. Ratione non est numquam iure a. Et illum provident iste nemo accusamus eum.', '1979-12-19', 'images/fake-image.jpg', 'Skylar Herman'),
(20, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Est temporibus nobis corporis aliquid quia ut.', 'Corrupti voluptatibus temporibus reprehenderit iste reiciendis est aperiam. Et facere rerum fugit molestiae iusto. Necessitatibus hic magni fugit sint voluptatem. Voluptatem quia commodi perferendis quam distinctio facilis dolor. Eos consequatur quaerat assumenda aut consectetur.\n\nIpsum tenetur ab delectus esse. Magnam rerum consequatur eveniet sint et numquam distinctio. Placeat consequatur voluptas et rem vel est.\n\nCulpa amet nesciunt architecto rerum dolorem maxime consequatur vel. Vel illo sint in nemo. Id ut qui facere et nulla earum velit. Neque voluptates error suscipit sed placeat placeat.', '1971-05-19', 'images/fake-image.jpg', 'Mr. Gilbert Dach III'),
(21, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Ipsum eum consequatur officiis quam officia.', 'Dolores qui dignissimos expedita maxime unde est. Voluptatem voluptatem alias et nostrum nihil excepturi. Repellat eaque voluptate enim aut ut vel sint. Est excepturi eum voluptatem nam tempora dicta.\n\nEst provident impedit quos eius sapiente perspiciatis ea. Ipsam quaerat delectus sint asperiores dolor et. Similique qui dolor dolore in. Architecto et corporis minima occaecati.\n\nEt sapiente nulla qui cupiditate. Architecto sit dignissimos quia enim ut vel. Dolorem velit eius repellendus est quidem quia. Quod numquam et soluta non reiciendis. Voluptatem vel dicta non deserunt accusamus ut.', '1994-11-05', 'images/fake-image.jpg', 'Mrs. Rebekah Bogisich DDS'),
(22, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quasi suscipit eos enim.', 'Minus sapiente nulla ad iure et impedit. Hic eligendi occaecati sit rerum est. At dolorem nam recusandae et. Ab architecto explicabo nihil dolor et aut.\n\nVoluptas cum quam dignissimos ratione. Sequi commodi sunt non deleniti est sed accusamus. Aut molestias sit nihil et alias voluptas corrupti. Expedita maxime et laborum nihil dolores laboriosam eius. Ipsum omnis repellat doloribus necessitatibus doloremque porro tempore omnis.\n\nPossimus voluptatem at ipsam sit. Porro amet sint veritatis voluptate. Corporis est aut distinctio aperiam et in eos.', '1997-01-25', 'images/fake-image.jpg', 'Eugenia Shields'),
(23, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolores occaecati commodi pariatur asperiores facere consectetur minima.', 'Quis molestiae dignissimos alias animi. Omnis aspernatur amet nobis voluptas sit id. Qui eaque voluptatem ducimus similique.\n\nSed dolores ut facere nihil non. Libero quo iste non ut consequatur aut consequuntur quam. Qui veritatis deleniti harum laboriosam pariatur.\n\nTempore labore aut debitis minima minus. Quo odio cupiditate consectetur animi. Dignissimos cum quaerat rerum sint ipsa illum. Ab nulla fugit ipsum itaque.', '1994-08-29', 'images/fake-image.jpg', 'Cristobal Prosacco'),
(24, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Provident enim ut et unde ut ut.', 'Quia rerum molestiae molestiae delectus vel quibusdam. Officia velit dolorem magni eius nobis iusto error.\n\nIllum omnis provident delectus aut aut minima. Beatae aut consectetur dolore quam. Itaque optio mollitia sequi odio qui.\n\nEt et corrupti error dolores quibusdam est nostrum. Dignissimos doloremque earum aut harum ea praesentium quis maiores. Tenetur impedit iste ad molestiae. Tempore provident enim ad ad.', '2018-08-12', 'images/fake-image.jpg', 'Daren Berge'),
(25, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Et perspiciatis cumque omnis tempora eos.', 'Omnis fuga consequuntur est. Molestias totam ab quidem eius. Ex nostrum adipisci sed beatae. Nobis modi qui recusandae.\n\nEst numquam minus nam omnis cumque doloremque. Eius qui optio officia dolor. Sunt natus natus repudiandae ut illo ratione ut. Eaque omnis eligendi libero.\n\nSed accusamus quibusdam accusantium. Eligendi id et dolores dolor rerum sit voluptas. Ut ut debitis sequi natus natus eveniet.', '2004-06-29', 'images/fake-image.jpg', 'Mrs. Itzel Turner Jr.'),
(26, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Modi ducimus reiciendis recusandae.', 'Voluptas rerum eligendi veritatis ipsa sed facere quibusdam sed. Tempora qui unde corporis inventore necessitatibus deserunt hic. Vel aut et eaque ut non quidem. Nobis qui culpa et itaque quae.\n\nIure aperiam ex est hic architecto ut. Provident similique optio eos et atque. Perferendis quam officia aut odio et animi debitis. Velit deleniti sed nisi ut ipsam repellat.\n\nVoluptatem molestiae numquam nemo amet reiciendis deserunt modi. Dolores voluptatem harum ea et nisi. Porro ea neque et doloremque.', '1978-09-13', 'images/fake-image.jpg', 'Jovanny Rippin DVM'),
(27, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Soluta dolorem optio error qui perferendis est.', 'Quis optio quis dolores voluptatem culpa sit eos aut. Autem blanditiis sint totam incidunt enim sed sit. Temporibus dolor ipsa sit omnis eius est magnam. Vel est eos nobis voluptatem.\n\nOccaecati aut voluptatem labore perferendis ut numquam. Reprehenderit provident at delectus rem. Earum ad odio quos.\n\nMagnam eum mollitia ut. Assumenda eum qui assumenda mollitia tempore. Ad distinctio repellendus quidem nam eius magni voluptatem. Dolores laboriosam molestias at est illum perferendis.', '2005-12-27', 'images/fake-image.jpg', 'Prof. Terry Denesik'),
(28, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Et dolorum unde quae ut voluptas iusto.', 'Iure architecto dolores nulla. Commodi similique est voluptates esse expedita ducimus quis vel. Ut tenetur consectetur impedit non impedit. Facilis laboriosam illo cumque expedita quod facilis qui.\n\nNostrum itaque iure possimus temporibus. Nisi debitis qui sit possimus nemo. Aliquam et nemo sequi vel incidunt et.\n\nLibero cupiditate excepturi eos dolore reprehenderit nostrum. Nemo quasi facere et. Quas nisi eius incidunt repellendus quia totam autem. Error vitae delectus qui saepe ab non.', '1992-03-08', 'images/fake-image.jpg', 'Dr. Herta Ryan'),
(29, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolores sed nemo quia necessitatibus velit.', 'Itaque laudantium nisi eos eveniet fuga fugiat qui. Cumque et culpa qui molestias. Corrupti sint soluta perspiciatis dolores vel enim. Ratione officiis itaque dolor nostrum.\n\nVoluptatem est nisi excepturi sed veritatis omnis. Commodi nobis nisi eum maxime dignissimos. Voluptas quis et autem cum cumque sapiente perferendis.\n\nNihil id aperiam laudantium. Explicabo nesciunt ut aut. Quod quia iste voluptas in aperiam corrupti. Tempore exercitationem hic velit ipsa reiciendis quod blanditiis.', '1978-11-10', 'images/fake-image.jpg', 'Mrs. Skyla Tremblay'),
(30, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Aut rem et eaque officia vel.', 'Doloribus ea porro ullam quis hic alias hic. Illo ut aut ut repellat. Et enim fuga vitae molestiae in. Illum veniam iure iusto aperiam ea.\n\nNulla explicabo voluptatem necessitatibus ea sed facilis. Ab molestiae officia cum dicta. Ipsa aliquam quo eligendi accusantium ex. Ratione et enim earum adipisci.\n\nAd eligendi consequatur harum sunt et. Rerum qui consequuntur amet. Repudiandae tempore quasi neque quam provident modi ut. Delectus vel est qui velit necessitatibus.', '1979-05-02', 'images/fake-image.jpg', 'Alejandrin Kassulke'),
(31, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Consequuntur quae nihil nobis sunt.', 'Doloribus porro pariatur voluptate qui officia eius. Voluptas expedita aperiam consectetur dolor autem est. Et quis nulla nobis placeat.\n\nError ut vel ducimus vero. Iure non et impedit voluptate. Sint ut est velit est est quas. Fuga iusto quibusdam non. Maiores quia voluptatum est explicabo.\n\nQuisquam beatae porro cumque. Omnis qui cumque perferendis sed aut. Accusamus quidem nulla nam adipisci itaque voluptatem ipsum blanditiis. Minus voluptatem ipsam sed quis. Facere dolore ratione debitis.', '2020-01-22', 'images/fake-image.jpg', 'Brown Stracke'),
(32, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Est ut ipsum aspernatur odio illum.', 'Quas deleniti ipsum qui optio maiores. Maxime ea et expedita ipsa provident. Quam id dicta at. Dignissimos ea deleniti id iure tenetur hic ex.\n\nAmet ratione veritatis repellat dignissimos distinctio. Doloribus adipisci qui soluta sapiente. Qui est non doloribus id harum voluptatibus.\n\nConsequatur illo odit voluptas dignissimos qui qui ut. Voluptate consequuntur sapiente recusandae. Quisquam et aut mollitia perspiciatis iusto perspiciatis sit. Temporibus consectetur iusto temporibus quam libero.', '1991-07-30', 'images/fake-image.jpg', 'Ms. Josie Kozey MD'),
(33, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Eum numquam voluptatem totam aut tempore.', 'Quas possimus dolorem ea. Quidem dicta voluptatem cum dolorem facilis iusto. Est et placeat sint accusantium quae nihil non quia.\n\nExpedita vel reprehenderit sunt tempora. Est consequatur ea ut quidem voluptates. Ut facilis id blanditiis consequatur doloribus.\n\nMagni architecto exercitationem molestiae corporis ut debitis minus. Iusto a neque enim ab ab blanditiis adipisci. Quo iure aut expedita.', '1971-04-23', 'images/fake-image.jpg', 'Desmond Collier'),
(34, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Distinctio hic et voluptatem omnis laborum impedit.', 'Exercitationem cupiditate praesentium et repellat ullam. Maiores voluptas dolorum maiores sed qui eos voluptates. Quis quibusdam possimus distinctio itaque earum.\n\nSit omnis dolore exercitationem qui. Illum impedit ab saepe quis. Laudantium et ipsam sequi quos voluptatem.\n\nEum debitis corrupti id aut quas debitis non quam. Aliquid illo cumque autem pariatur hic maxime minima et. Atque ab necessitatibus ratione magni.', '1982-02-17', 'images/fake-image.jpg', 'Dr. Sarah Balistreri'),
(35, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Veritatis quia dolorum quam debitis.', 'Porro et est rerum omnis. Ut vel tenetur sit error adipisci. Similique et provident quis dolorum dolore in. Eum voluptates veritatis aut explicabo quis. Consequuntur aut numquam aut minus quod.\n\nQuidem illo qui qui culpa aliquid voluptatem. Cupiditate iure non fugit nisi autem. Praesentium ducimus ut non iste ut nulla.\n\nBlanditiis alias dolorem quibusdam consequatur enim. Odio quisquam mollitia sunt. Asperiores quia temporibus veniam quidem recusandae. Consequatur rerum ut placeat incidunt commodi quo quia.', '1997-11-29', 'images/fake-image.jpg', 'Dallin Wunsch'),
(36, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quo consequuntur qui ea et vel distinctio aut adipisci.', 'Sunt reiciendis earum sed pariatur nihil. Enim aliquam voluptatem vero molestiae culpa.\n\nMagni et laboriosam sed voluptas atque. Est occaecati et quibusdam quia ducimus dignissimos. Id quia consequatur in qui ipsa modi.\n\nTenetur et nihil magni magni eaque consequatur omnis. Veniam velit veniam cum nihil laboriosam necessitatibus eaque nihil. Ut voluptates qui totam similique ullam perferendis. Fugiat deserunt assumenda quo modi.', '2004-01-06', 'images/fake-image.jpg', 'Foster Jones'),
(37, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Labore et provident ipsa ratione ratione mollitia iste.', 'Culpa veniam enim error maiores doloribus aspernatur ut. Culpa molestiae et totam atque sit. Magni pariatur aut aut at. Quia quo vitae fugiat perferendis.\n\nNon voluptatem accusamus sapiente minima debitis incidunt at. Fuga a ratione quo excepturi est. Beatae a id molestias est hic consectetur similique omnis.\n\nRecusandae voluptas fugiat enim ut sint ex est nostrum. Sed omnis neque alias blanditiis est sed illo. Nobis est delectus temporibus molestiae ut quae.', '1972-08-04', 'images/fake-image.jpg', 'Prof. Khalid Berge PhD'),
(38, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Provident quaerat qui deleniti sed nemo quas est.', 'Dolor dolor voluptate neque quia cum. Distinctio similique explicabo quisquam quis quis soluta quidem. Saepe commodi perferendis nam aliquam quo et qui voluptas.\n\nId eligendi velit dolorem alias. Eaque qui quia voluptatibus consequatur impedit dolor maiores totam. Aperiam sapiente nemo non autem illo.\n\nAliquid eaque exercitationem eligendi eum numquam in. Et corporis ullam sed magni in. Et voluptatem atque et eius. Libero voluptatem occaecati temporibus ea nisi deserunt.', '1994-04-24', 'images/fake-image.jpg', 'Natasha Huel'),
(39, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Sequi perferendis alias corrupti et neque.', 'Quasi in tempora dolor quae. Vitae enim sit modi a.\n\nSed repellendus quis nihil asperiores enim magni. Accusamus sint ut eum nisi. Laboriosam aliquid autem dolorum non.\n\nEt id et sunt explicabo esse ab aliquam. Omnis a aut expedita distinctio. Porro enim accusamus occaecati eos qui et.', '1979-06-08', 'images/fake-image.jpg', 'Prof. Keenan Cartwright Jr.'),
(40, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Ad non pariatur suscipit iure aliquam in sunt ut.', 'Quisquam ipsa rerum vero debitis voluptatibus perferendis omnis. Et ipsam veniam voluptate adipisci fugiat. Enim aliquid inventore et commodi enim harum numquam. Reiciendis asperiores ea in non sed at voluptas omnis.\n\nRerum numquam magni impedit porro. Et possimus et optio nihil reiciendis consequatur aut. Dolor voluptatum est quisquam distinctio quis sit sed. Eaque sint ut libero deserunt numquam ad.\n\nVoluptatem expedita eaque nesciunt molestias. Qui reiciendis unde esse nihil maiores et. Totam id quis error deleniti. Nulla aspernatur animi veritatis officia corrupti.', '2015-07-10', 'images/fake-image.jpg', 'Carmen Haag'),
(41, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Nostrum est quia qui omnis inventore.', 'Et nemo assumenda atque vel. At harum dolor earum nostrum. Tenetur quibusdam ut quo corrupti natus.\n\nTemporibus id nemo adipisci laboriosam ut consequatur. Qui aliquam vel magni quos inventore. Accusamus voluptatum quas consequuntur cumque doloribus aut. Et saepe maiores eos minus.\n\nSoluta ullam vero ut. Exercitationem dolorum ipsa et delectus explicabo. Adipisci temporibus incidunt atque ducimus natus similique.', '1985-06-10', 'images/fake-image.jpg', 'Greg McClure'),
(42, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dicta omnis numquam recusandae cum sed sed beatae distinctio.', 'Labore et mollitia porro sit. Modi voluptates tempore quia dolor ducimus aperiam aut et. Aliquid deleniti illum quia. Reprehenderit ut quia reiciendis inventore doloremque accusantium quis.\n\nEt odio quisquam iste autem dolore et. Fuga voluptas possimus exercitationem rem asperiores quod. Est qui dolorem non explicabo iusto dolor quo.\n\nConsectetur sed distinctio quae officia aut. Et consequatur quia totam ea facilis ex quibusdam consectetur. Quas et quis reiciendis ducimus illum.', '1998-12-10', 'images/fake-image.jpg', 'Dr. Manuela Fay'),
(43, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolores quam voluptatibus excepturi non accusamus odio.', 'Tempore harum nostrum fugiat aspernatur. Rerum vitae voluptas natus. Magni et explicabo perferendis quae eum. Ut dolorum voluptatem culpa perspiciatis sed porro nulla. Ad praesentium accusantium a repudiandae saepe quam doloribus.\n\nEsse totam atque labore sunt nesciunt earum. Aut mollitia nisi provident nisi. Et dignissimos voluptas qui voluptatum nulla adipisci suscipit. Temporibus aut quia asperiores quas fuga. Asperiores quo aut dolorem est facere accusamus.\n\nNesciunt et quas sunt. Et deserunt tempore vero non quos qui incidunt. Quas et quisquam sit voluptatem minus et. Et occaecati dolor vel et aut et. Consequatur quod laudantium est cum repellendus.', '2008-04-20', 'images/fake-image.jpg', 'Treva Boyer'),
(44, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Iure repellat aliquam velit vero.', 'Inventore aut blanditiis iure asperiores velit. Ratione doloremque quas temporibus aut. Maiores ut ut excepturi aliquam ab nihil ipsum quae. Ea officia deserunt illum vel consequatur beatae.\n\nNostrum aperiam soluta consequatur. Aspernatur consequatur numquam eum omnis et asperiores voluptatem. Eum quia est ea. Laudantium sunt est ea.\n\nNon dolorem delectus laboriosam in magnam. Quasi quibusdam expedita voluptatibus voluptatem vitae dolorum rerum.', '1970-10-13', 'images/fake-image.jpg', 'Carole Fadel'),
(45, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Accusantium praesentium animi tempore voluptates quas placeat dolores aut.', 'Commodi soluta consectetur aut aut dolorem. Odit facilis fugit vel quas illo dignissimos totam. Quia eum et sed est aut nam. Esse quia voluptates dolores exercitationem numquam ab voluptates. Quia aperiam totam ipsam ut est.\n\nNisi dolor fugit numquam eaque libero veritatis. Perferendis reprehenderit qui aut autem sunt sunt. Nemo animi iure autem est.\n\nFacere veritatis molestias quisquam molestiae. Nulla beatae voluptatem qui. Perspiciatis possimus accusamus reprehenderit corrupti sed. In ut accusantium nulla incidunt nisi quae.', '1972-09-04', 'images/fake-image.jpg', 'Audrey Gerhold'),
(46, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Explicabo ratione libero earum veniam laborum dolor.', 'Sit repellat consequatur odio. Libero nam totam non eum ut et quia. Accusamus et cupiditate eum ut sint.\n\nConsequatur quia doloribus sit quo. Labore rerum atque est expedita reiciendis et architecto. Alias est expedita natus provident excepturi labore.\n\nUllam assumenda sint quae porro quos sit corrupti. Officiis et eius adipisci inventore sed qui totam. Qui et magnam aspernatur. Veniam nisi aut molestias sint qui quis. Eos facere alias maiores ut ut.', '1991-02-15', 'images/fake-image.jpg', 'Miss Angelica Tromp IV'),
(47, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Voluptatibus et unde et repellat veritatis.', 'Occaecati neque tenetur sint voluptatem ut. Molestiae voluptatem esse et quo sit qui. Ab nisi voluptatem non nesciunt adipisci.\n\nAutem cumque molestiae ab. Accusantium aut architecto eius. Eaque qui nesciunt est iste alias eaque.\n\nAd perspiciatis ipsa quia et aliquam dolorem. Soluta ea iure vitae labore voluptas nihil. Et voluptates minima et dolorem nihil dolore officiis. Voluptatem a officia deserunt consequatur nobis illo eum.', '2003-02-06', 'images/fake-image.jpg', 'Sedrick McClure'),
(48, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Unde aut est id et.', 'Hic animi nihil est dolorem ut. Veritatis eaque qui aliquid molestiae. Quo mollitia qui iure et. Officia saepe ducimus fugit natus doloremque voluptatum et. Quasi sapiente et non.\n\nVeritatis sit qui velit atque. Esse quia doloremque exercitationem eveniet. Beatae ullam officia est quam in.\n\nDoloribus hic aliquam dignissimos similique ut laborum necessitatibus. Cupiditate harum quasi voluptates quos vel numquam quidem. Delectus dolor ullam qui nesciunt doloribus qui nulla adipisci.', '1989-10-31', 'images/fake-image.jpg', 'Prof. Jaeden Reinger'),
(49, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Doloribus expedita doloremque libero sunt eaque dolorem doloribus suscipit.', 'Non maxime exercitationem laboriosam ipsum eum. Quia et exercitationem voluptatem quaerat hic maxime quo. Dignissimos et dolore architecto soluta asperiores.\n\nRatione nostrum vel repellendus. Praesentium quam quod cupiditate perferendis. Porro officia debitis voluptate iure omnis qui.\n\nSint omnis modi aut suscipit dicta qui. Rerum recusandae corrupti sequi animi. Eaque quod libero sed eum.', '2017-08-02', 'images/fake-image.jpg', 'Prof. Dexter Pacocha MD'),
(50, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quibusdam minima delectus blanditiis et quia.', 'Aut adipisci cupiditate dignissimos similique. Quis repudiandae odit explicabo dolor. A accusamus vel deleniti enim aut aut.\n\nRepellat itaque possimus alias suscipit architecto quidem. Voluptatum eveniet illum vero saepe fugiat repellat natus. Voluptatibus dolores pariatur nisi quibusdam sed voluptatum minima. Maxime dolorem error qui officia odio voluptatem perspiciatis. Est in quia molestias et rem.\n\nDolores minima sapiente impedit hic sunt vel aut occaecati. Perspiciatis quod velit ducimus dolore. Quia ab pariatur numquam expedita autem. Qui ut dolorem magnam quasi ut aliquam.', '1979-05-22', 'images/fake-image.jpg', 'Efren Tillman'),
(51, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Atque laudantium dolorem delectus fugit et quis.', 'Animi atque labore reiciendis perspiciatis est neque ad iure. Velit facere rerum ipsam et. Placeat unde delectus molestiae aperiam.\n\nBlanditiis asperiores ut maiores. Sunt hic qui voluptas et officiis est officiis. Fugiat vel molestiae consequatur iure eos et odio.\n\nMolestiae laudantium cum molestiae fuga. In quos distinctio et amet. Nihil non quod et dolores. Dignissimos cum repellendus illum voluptatem nulla.', '2000-10-20', 'images/fake-image.jpg', 'Luisa Witting'),
(52, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Molestiae sequi rerum id illum vitae modi doloremque doloremque.', 'Magni doloremque nobis assumenda voluptatem eligendi ut. Et quis eaque commodi ut atque fugiat. Culpa molestiae voluptas possimus nesciunt non labore dolorem id. Unde eos qui itaque.\n\nEt iusto porro cum nulla et. Vitae possimus rerum sed fuga eligendi harum suscipit. Minima repellendus officiis sint quaerat iusto eos libero.\n\nAut sint soluta voluptatem voluptas voluptatem consequuntur. Fuga aspernatur est architecto ea earum tempora. Maxime et sequi dolores tempore. Tenetur quod ut eum sit occaecati nostrum.', '1971-10-20', 'images/fake-image.jpg', 'Miss Cortney Sauer DVM'),
(53, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Omnis rem explicabo consectetur repudiandae.', 'Quidem omnis accusantium quos sit aut tempore. Qui exercitationem doloribus nobis adipisci. Nemo magni tempora quis enim harum. Numquam blanditiis sequi et est minus.\n\nBeatae saepe at autem sit sed qui. Provident rerum rerum voluptatem asperiores ut nulla. Quia libero est adipisci et consectetur.\n\nMagni optio consequuntur sed harum quod aut. Aspernatur quia velit amet et consectetur. Occaecati illum nisi est veritatis ut cum voluptate nulla. Laudantium non velit amet est aliquam dolore.', '1970-12-03', 'images/fake-image.jpg', 'Phoebe Schmeler'),
(54, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Ipsam quisquam consequuntur animi numquam qui aut blanditiis.', 'Saepe ratione cum qui magni consequatur consequatur. Earum vitae nihil natus eligendi. Quo soluta nihil velit aperiam maiores. Dicta quis dolores qui aliquam aut impedit.\n\nAlias est voluptas nobis quo non dignissimos. Aut vel pariatur nostrum esse maxime. Nulla placeat omnis iure quo tempore. Qui voluptates saepe in ut et et cumque.\n\nEnim doloremque voluptatibus fugiat id ratione illo. Harum doloribus accusamus maiores minus ut blanditiis hic. Voluptatem error delectus accusamus animi possimus. Eos ab eligendi quas amet quis eum quas. Perferendis eos rerum in ut.', '1983-06-03', 'images/fake-image.jpg', 'Eulah Legros'),
(55, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolorem fugiat consequuntur facilis iste quis.', 'Cumque voluptatum tempore quod id veniam aut. Totam est deserunt voluptates exercitationem assumenda. Omnis voluptatibus nihil numquam illum corporis itaque. Laborum sit sequi eaque doloribus.\n\nMolestiae ea sunt laboriosam ipsum quae. Aut voluptatum voluptas fugiat quo velit iste. Quam explicabo pariatur quia velit totam aut.\n\nQuia ipsum veritatis vero veritatis facere. Labore ut quia temporibus. Quas modi consequatur alias eius quia. Nemo quisquam est quia repudiandae magnam enim similique.', '1984-06-05', 'images/fake-image.jpg', 'Caitlyn Marks DVM'),
(56, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolorum sit et consequatur sit.', 'Voluptatem nulla voluptas nisi rerum. Ut dolore molestiae voluptas sit et. Nulla itaque soluta et eius.\n\nInventore aut fugit voluptas rerum ex ratione distinctio. Repellendus velit dolores nostrum rerum sint inventore quisquam.\n\nVoluptatum aut est expedita voluptates. Enim rerum consequatur exercitationem iste excepturi consequatur. Quis voluptatibus nisi est quia.', '2023-01-05', 'images/fake-image.jpg', 'Sedrick Powlowski V'),
(57, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Consequatur recusandae libero ut eius.', 'Est et dolorem qui. Incidunt nemo animi ut excepturi corrupti ea dolor. Dolores et quod quia laborum debitis est quos autem.\n\nCulpa eveniet repudiandae distinctio autem. Fugit dolores tempora non eligendi esse hic. Non odio quos in. Suscipit est neque quasi consectetur maiores et corporis.\n\nDoloribus corporis cumque consequatur ea. Et unde ut sunt voluptatem. Voluptas cupiditate unde aut quo reiciendis natus. Saepe est incidunt eos consequuntur qui modi consequuntur doloribus. Deserunt beatae tenetur earum ea sed dignissimos officia explicabo.', '1996-04-20', 'images/fake-image.jpg', 'Shanon Wilderman'),
(58, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Accusamus dolores autem delectus optio id.', 'Tempore quidem repellat saepe eum laudantium. Sed maiores voluptatum impedit quia et. Omnis voluptatem nihil consequatur.\n\nMaxime sint illo sed enim. Iure exercitationem aut voluptatum. Autem et distinctio dolorem.\n\nQuia reprehenderit illum assumenda similique. Fuga soluta aut ipsam esse. Est reprehenderit voluptatem quia soluta adipisci voluptatum.', '1985-10-20', 'images/fake-image.jpg', 'Ruthie Collins DVM'),
(59, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Sed et voluptatibus vel odit neque veniam.', 'Necessitatibus et vitae consequatur nihil. Possimus quia eos rerum eligendi ratione reprehenderit fuga nisi. Velit impedit totam dicta expedita enim quibusdam et.\n\nAut ut et est quo blanditiis facere dicta. Odit est quaerat unde dolores. Eum voluptas repudiandae asperiores tempore. Consequatur id similique eos cupiditate ut quo.\n\nOmnis et velit laboriosam ut dignissimos doloribus omnis. Dolorem est reiciendis corrupti dicta ipsa.', '1989-05-06', 'images/fake-image.jpg', 'Roxanne Hettinger'),
(60, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Repellendus et voluptatem est consequatur harum et eius.', 'A vel soluta cumque mollitia et delectus amet. Dicta dicta perspiciatis delectus consectetur rerum. Enim a quidem iure. Incidunt ut cumque rem est. Et similique a voluptatum consequatur provident.\n\nInventore quis voluptatem veritatis unde optio. Exercitationem magni sunt enim voluptate. Animi quia id iusto harum quos. Optio iusto et excepturi reiciendis. Quo sequi doloribus repellendus sequi.\n\nDignissimos minus inventore non quod possimus autem. Corrupti ratione quos suscipit odio fuga eos magnam. Asperiores similique molestias ad fugit pariatur necessitatibus exercitationem. Adipisci modi id saepe fugit dolores excepturi.', '2000-02-05', 'images/fake-image.jpg', 'Micheal Sporer'),
(61, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Ut tempora atque autem adipisci nihil ut.', 'Neque culpa quo delectus. Nostrum qui quo iure sit a. Necessitatibus libero cupiditate distinctio aut est consequatur.\n\nIncidunt facilis ut iusto itaque beatae aperiam aut qui. Nesciunt quisquam quasi dignissimos ratione quae. Omnis distinctio repellat maiores veniam quo molestias perferendis. Earum doloribus laboriosam est optio sit fuga eum accusamus.\n\nAperiam qui at quia veritatis ducimus perspiciatis. Quo et itaque adipisci molestiae rerum.', '2018-08-13', 'images/fake-image.jpg', 'Joaquin Carroll'),
(62, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Sequi ut porro quaerat repudiandae.', 'Sapiente quos nam sed quo. Facilis debitis quibusdam nostrum perspiciatis ab et nesciunt ullam. Debitis perspiciatis assumenda earum sapiente enim.\n\nAnimi quos eveniet quos soluta sequi ut. Molestias qui veritatis accusantium facilis. Eos id quod voluptas nostrum error aut. Illo expedita aut delectus distinctio aspernatur voluptatum.\n\nExercitationem et possimus voluptates. Amet cum tempore voluptas reiciendis facilis. Explicabo qui ducimus consectetur voluptatibus qui soluta doloribus. Corrupti voluptates voluptatem expedita.', '1973-09-18', 'images/fake-image.jpg', 'Lilla Wolf'),
(63, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Veritatis maxime ullam quidem qui voluptatem.', 'Quo est et nihil laudantium unde impedit. Hic aut sint qui in nisi nesciunt. Voluptatibus molestias nobis facilis quidem dolorem. Ut quia nemo ducimus ut quo aut non.\n\nProvident debitis voluptatem harum quia asperiores est laboriosam. Est totam adipisci architecto nostrum maiores. Est aut repellat sint incidunt nobis nulla ut. Explicabo mollitia adipisci nulla architecto.\n\nTenetur ut repudiandae est ea natus sunt accusamus ab. Fuga molestiae veniam eum repudiandae doloremque perspiciatis voluptate. Non nemo aspernatur quia debitis hic. Cum atque numquam dolores dolor eos aliquid fugiat omnis. Et rerum voluptas impedit sit et aut delectus.', '2008-01-31', 'images/fake-image.jpg', 'Rosendo Bradtke'),
(64, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Consequatur qui tempore quae doloribus quibusdam aspernatur veritatis.', 'Quia corrupti sapiente optio molestias dolorem. Laborum sint delectus tempora voluptatem molestias. Aut rerum ut in eveniet. Id ut itaque beatae ea ratione consectetur illum vel.\n\nAliquam sapiente illo voluptatibus debitis ullam quo illo. Suscipit rerum rerum aut corrupti. Officiis quam neque non libero consequuntur ut ad numquam. Veritatis sunt et nihil sed itaque est reiciendis nulla. Iure reprehenderit est alias necessitatibus.\n\nEst voluptas at consequatur cupiditate autem fuga ut. Dolores consectetur aut vel qui veniam.', '1997-08-08', 'images/fake-image.jpg', 'Mr. Chadd Hackett'),
(65, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quae iusto numquam qui asperiores ea ab est.', 'Occaecati ut labore unde quia rerum dolore enim possimus. Suscipit quia doloribus praesentium sed sequi nam adipisci. Molestias quasi exercitationem pariatur esse et impedit nobis mollitia. Est at sint assumenda et a non ipsa.\n\nExpedita eius molestiae reiciendis aliquam ut rerum. Ad enim provident veritatis molestiae aspernatur labore. Quas rem rerum nesciunt veniam. Cupiditate aut sunt omnis quam voluptas.\n\nIn assumenda voluptatum sint aut sed eligendi repellendus repudiandae. In commodi quo ut illum. Officiis sunt rem quasi iusto. Molestias ab autem cumque magnam labore dolore. Dicta qui quia ducimus pariatur fugit.', '1971-06-15', 'images/fake-image.jpg', 'Dolores Homenick DDS'),
(66, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Sint est aliquam rerum nulla vel enim libero.', 'Provident omnis quo minima inventore et quo. Quia vel iste maxime veritatis enim commodi quod quia.\n\nVoluptatem dicta repellat magnam incidunt ut consequatur aut. Quia ab neque qui quas cupiditate esse ratione. Porro illo sed modi et architecto consequuntur. Assumenda vero voluptas assumenda aspernatur repellendus ut ut.\n\nRerum quaerat dolores maiores accusamus deserunt ad. Quis modi inventore vitae nobis. Sit laudantium minima doloremque porro odio voluptates distinctio.', '2002-05-15', 'images/fake-image.jpg', 'Gladys Zboncak Sr.'),
(67, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Aliquid voluptas repudiandae quasi fugiat sed et unde.', 'Qui doloribus tenetur magni reprehenderit rerum aut sequi. Quae alias suscipit et at sapiente autem facere rem. Beatae autem est et. Autem quo dignissimos molestiae.\n\nLabore sed itaque aperiam quidem accusamus debitis. Voluptatem dolores et voluptate voluptas doloremque est distinctio rerum. Magnam iure dolores sunt expedita vel reiciendis quia. Repellat reprehenderit cum ullam non qui sapiente consequuntur est.\n\nQuis aut sunt in voluptas. Libero assumenda molestiae omnis sed. Cupiditate id labore aut.', '2017-11-09', 'images/fake-image.jpg', 'Edd Swift'),
(68, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quasi tempora repellendus delectus eveniet qui nesciunt optio.', 'Et voluptas laudantium dicta inventore. Dolorem porro quia accusantium qui excepturi autem libero autem. Iure qui dolor repellat aut. Iste est veniam molestiae odio non et voluptas.\n\nPossimus et assumenda accusamus placeat omnis. Sunt quia ea molestiae ducimus neque voluptas. Quas molestiae repudiandae reiciendis eveniet molestiae.\n\nEos consequatur nobis ad aliquam quia. Quia quidem consequatur laudantium inventore incidunt inventore. Culpa id aut et quo ut. Hic totam sit animi praesentium.', '1972-04-01', 'images/fake-image.jpg', 'Shanie Pouros'),
(69, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Et vel modi vel.', 'Nulla ipsum et ut perferendis qui. Reprehenderit dolores aspernatur sit voluptas similique eos. Ad ea ut omnis possimus. Non recusandae rem eum ipsa voluptas et enim. Doloribus qui fugit voluptates quo qui esse.\n\nDolorem voluptas molestiae maiores consequuntur debitis. Veritatis fugiat sint tempore.\n\nAutem veniam eos aut impedit et dicta. Earum vel quas error rerum dolor quia itaque magni. Sit nulla itaque consectetur velit dolor eum similique. Est sint nihil molestiae suscipit dolores ullam labore.', '2018-01-25', 'images/fake-image.jpg', 'Evans Pfeffer'),
(70, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Consequatur explicabo aperiam dolores adipisci nostrum magni.', 'Odio necessitatibus quibusdam unde fuga repellat. Numquam et officia culpa sit. Quos dolorum exercitationem perferendis voluptatem et occaecati.\n\nNeque et molestias recusandae quos natus. Sit consequatur facilis odit ut. Et nam iste ut magnam. Ut nihil maiores pariatur debitis consectetur.\n\nDistinctio nostrum delectus pariatur molestiae aliquam illum. Assumenda maxime enim consequatur doloribus harum qui. Eveniet ad nostrum quia earum et necessitatibus. Quo quo sit id autem et et eligendi officia.', '2019-09-28', 'images/fake-image.jpg', 'Ms. Paula Denesik'),
(71, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'A molestiae et deserunt quis ea occaecati soluta.', 'Dignissimos nulla cupiditate laudantium sed dolor. Dolor non quis aut iste quis praesentium possimus consequatur. Aut dolor id recusandae.\n\nMagnam ab alias ipsam maiores voluptas. Ullam et magnam consectetur.\n\nQuasi et ratione aut rerum sed vel qui. Magnam occaecati eligendi eveniet distinctio consequuntur. Dolor eveniet ducimus ipsam velit voluptatum. Voluptas eos aut rerum adipisci.', '1975-05-09', 'images/fake-image.jpg', 'Marlee Ledner'),
(72, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Omnis deleniti neque consectetur.', 'Et dolores sit perspiciatis. Aut impedit consectetur adipisci voluptas eos. Nihil a aut ut quia consectetur repellat quis.\n\nOdio voluptatum aliquam itaque eius officiis officiis. Ea velit dolorem harum sunt. Beatae eveniet natus odit asperiores asperiores quisquam quod. Laudantium sequi aut quae repellendus consequatur illum quibusdam maiores.\n\nVoluptatem possimus repellendus fugit laborum consectetur. Voluptates quos dignissimos et ut modi. Deleniti et et sit sit.', '1982-11-18', 'images/fake-image.jpg', 'Reilly Bosco'),
(73, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Sed ut quae voluptas voluptatem sint voluptate.', 'Porro beatae molestiae nihil et est quia et. Nulla rem odio debitis nostrum quia beatae porro. Necessitatibus natus doloremque reprehenderit perferendis quaerat esse ut.\n\nMinima aut nihil dolorem voluptatem perferendis. Quo minima ipsam vel dolorem totam. Culpa sed veniam numquam vel quia voluptatibus. Dolorem provident et dolorem perspiciatis reiciendis.\n\nNulla voluptas qui eveniet deleniti occaecati veniam eveniet. Esse pariatur ipsum numquam ad commodi doloremque vel aliquid. Laudantium nisi voluptatem quasi dolores et.', '1995-07-05', 'images/fake-image.jpg', 'Prof. Price Hodkiewicz');
INSERT INTO `noticias` (`id`, `created_at`, `updated_at`, `titulo`, `contenido`, `fecha_publicacion`, `imagen`, `autor`) VALUES
(74, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Odit voluptatem aut consequatur tempora.', 'Fugit ipsam corporis laudantium qui perspiciatis. Quis est voluptatibus sit consequatur. Dolores harum fugiat necessitatibus neque doloremque eaque. At doloremque quam ducimus unde ea.\n\nQuo velit quod sit incidunt consequatur. Et distinctio esse officiis error odit. Eligendi tempora nihil totam.\n\nQuo accusamus expedita officiis magni ut. Expedita tempore ipsa dolorem. Tenetur quo optio illum perferendis est.', '2013-08-27', 'images/fake-image.jpg', 'Clare Harber DVM'),
(75, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Corrupti amet quo necessitatibus laborum eos rem.', 'Sunt qui beatae qui cum et aut. Maiores ipsam accusantium alias perspiciatis et molestias consequatur. Eius minima aut mollitia velit. Eius ad impedit ut porro.\n\nSimilique ex fugit a non. Voluptatem quibusdam architecto consequatur qui aut est. Recusandae excepturi unde veritatis aut corrupti beatae expedita quo.\n\nDeserunt quis amet voluptas enim accusamus iure explicabo. Odio eveniet tenetur consectetur ad ut enim. Sunt dolor illum et aliquam placeat est. Molestias amet sunt assumenda nemo nostrum doloribus.', '2020-04-10', 'images/fake-image.jpg', 'Dr. Sydnee Steuber V'),
(76, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Molestias consequuntur quo recusandae sapiente.', 'Quae ut quo quod id. Rerum et odit aspernatur molestiae est hic voluptatem. Facere quis voluptatem natus. Cupiditate voluptatum et minus explicabo impedit illo.\n\nQuae sed quaerat aut. Dignissimos dolorum eum tenetur aliquid. Possimus sit animi et et soluta.\n\nEst excepturi fugiat quia autem qui et facere. Debitis voluptas praesentium unde eligendi sit. Eveniet aut velit exercitationem et.', '1970-12-28', 'images/fake-image.jpg', 'Miss Yadira Cole'),
(77, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Laboriosam non a incidunt esse quidem ut ut repellat.', 'Doloribus in esse ad ab. In qui labore quasi explicabo magnam. Accusamus suscipit officiis aut nam accusamus odit rerum. Consequatur voluptatum possimus asperiores est sapiente repellat.\n\nIllum dicta libero corporis illum eius repellat. Qui est alias perferendis est soluta. Quis sed consequatur sit voluptas rerum laudantium. Facere quod ut deleniti voluptatem.\n\nVoluptatem reiciendis distinctio quia autem quidem. Quia at quis consequuntur eum laudantium nihil id. Ut autem modi quia quasi error voluptas occaecati.', '1978-07-12', 'images/fake-image.jpg', 'Miracle Daniel'),
(78, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Doloribus soluta ut dolor magni.', 'Architecto possimus necessitatibus natus aut velit voluptatem. Quis non amet dolorum at at. Est sunt ut commodi tenetur voluptas nihil est. Vitae perferendis eveniet animi qui suscipit similique.\n\nOmnis distinctio quia nobis sunt voluptas. Dolores odit id dolores dolor in. Explicabo maxime ex a dolorum vero.\n\nIllo maxime aut alias architecto esse sit. Omnis porro sunt aut vero cumque sed suscipit. Sunt adipisci quos ut similique sapiente autem repudiandae voluptates.', '1986-01-11', 'images/fake-image.jpg', 'Enrique Wyman'),
(79, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Similique nisi libero voluptatum deserunt nisi expedita et.', 'Placeat facere et labore ea perspiciatis non. Mollitia harum quasi iusto quisquam ut modi error. Exercitationem blanditiis odio laborum nihil cum.\n\nFacilis nihil quis facere quis aspernatur. Mollitia labore amet voluptatem cumque sapiente quam. Qui molestiae expedita fuga quos.\n\nNatus voluptatem et eos accusamus. Cum ipsam illo distinctio occaecati eos voluptas asperiores. Excepturi officiis modi id voluptatibus dolorem minus.', '2018-12-03', 'images/fake-image.jpg', 'Rosamond Carter'),
(80, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quo inventore ullam dolorum expedita quasi non quaerat.', 'Tempore optio magnam mollitia. Voluptate nulla veritatis incidunt dolorem. Aut aut ut voluptatibus dicta iure aspernatur voluptatum. Aut odit et aut similique accusamus.\n\nMinima commodi perferendis odio ipsa quae. Tempora inventore et excepturi expedita repudiandae quia sequi. Debitis aliquam delectus dicta aliquid iusto suscipit.\n\nTemporibus laudantium sunt est qui illo. Velit iusto corporis voluptatem autem commodi et quisquam. Vel odit id ea dolorem et fugiat. Incidunt eum reiciendis cupiditate veritatis. Cupiditate esse et dolorum.', '2009-02-08', 'images/fake-image.jpg', 'Marisol Harvey'),
(81, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolores omnis vel et aut accusamus suscipit.', 'Ratione reiciendis eius vitae aut. Necessitatibus nisi eveniet quasi et molestiae repudiandae ipsam praesentium. Nostrum fugit doloribus dolorem culpa eum omnis corrupti.\n\nReiciendis qui et velit quod. Omnis tempora veniam eligendi voluptate. Nemo iste reiciendis quis expedita cum enim. Qui voluptate modi quos.\n\nQuis rem quo sunt maxime et aut minus. Voluptatem ducimus delectus similique nostrum rerum. Impedit maxime et ex magni aut quasi laudantium ducimus. Accusamus et sit placeat aut quia.', '2022-09-09', 'images/fake-image.jpg', 'Enid Dicki'),
(82, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Nulla quisquam id nihil accusamus minima aut.', 'Magni repellat vel ipsum inventore. Sint occaecati nam quas neque asperiores. Ut quo accusamus non cumque exercitationem modi in quidem. At aliquam blanditiis at veniam id nihil.\n\nSunt consequatur id fugiat quia. Eos aut odit asperiores necessitatibus. Sapiente mollitia modi soluta quae. Repellendus fugit eos aliquid accusamus hic.\n\nPerferendis nesciunt eaque ea sint quae qui tenetur. Quidem sint unde autem unde deleniti. Numquam debitis laboriosam ipsa ut libero. Consequatur et sunt soluta est repellat. Cupiditate ullam porro omnis accusantium qui sunt sunt.', '1979-10-09', 'images/fake-image.jpg', 'Trace Hessel IV'),
(83, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Qui dicta enim laborum repellendus nulla id est.', 'Minus quae eaque quas rerum nesciunt. Autem est asperiores quaerat facilis quisquam. Iure cupiditate rem quia magnam. Odio in quia nobis et.\n\nA at sit qui odio assumenda eligendi. Est voluptatem rerum doloribus at itaque nisi modi.\n\nSit perspiciatis omnis facere et provident. Unde voluptate tempore culpa quisquam debitis natus. Id qui autem illo eum exercitationem non pariatur.', '2001-08-25', 'images/fake-image.jpg', 'Mr. Edwin Considine'),
(84, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Aut laboriosam atque reiciendis sit.', 'Repudiandae sint nostrum odio omnis. Doloremque delectus nihil non non. Impedit numquam doloremque cumque dolore. Et doloremque eum quae temporibus. Voluptatem quis deleniti nesciunt quia fuga.\n\nEos impedit minima temporibus qui illo consectetur voluptatum sunt. Rerum vel non ut consequatur quia nemo animi. Fuga quas ea voluptatibus doloremque. Quae beatae possimus officiis.\n\nQuae iusto officia molestiae iste deleniti veritatis. Rem dolorum odit quia qui. Recusandae ullam molestiae eligendi et non aut perspiciatis. Animi assumenda magnam quibusdam voluptatum et natus eos. Et qui ratione molestiae labore commodi.', '1992-10-19', 'images/fake-image.jpg', 'Matilda Schmidt'),
(85, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quaerat at autem ut dolorum nesciunt inventore.', 'Et quod amet unde expedita quo nulla vero. Nisi nisi eos nesciunt doloribus voluptates. Sequi officia et recusandae sequi. Culpa tenetur et architecto.\n\nRepellendus officiis voluptatem consequatur et ducimus repellat voluptas. Suscipit et facere voluptas esse. Deserunt quas in aut doloribus rem. Nihil tenetur necessitatibus ut sint.\n\nQuia est eos exercitationem ex debitis amet nemo. Nesciunt autem et consequuntur. Adipisci maxime temporibus odio et unde omnis. Qui voluptatem repellendus maxime deserunt voluptatum ut quis.', '2021-05-06', 'images/fake-image.jpg', 'Justus Rolfson'),
(86, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Exercitationem nihil ex reprehenderit quo iure.', 'Doloremque et eius perspiciatis et consequatur sunt. Ex et libero quod est doloribus est. Voluptates eveniet id provident. Consequatur unde aperiam officia eos animi.\n\nNam ut quasi quis fugiat doloremque iusto accusamus. Voluptatum aliquid rerum voluptatibus dolor deleniti rerum minus. Ipsa fugit voluptatem laudantium sunt consequatur. Consequuntur qui pariatur et totam sint deleniti.\n\nExplicabo ut sapiente fugit porro iure eveniet. Nemo inventore aperiam commodi suscipit qui voluptas voluptatem. Atque eos quia aperiam distinctio necessitatibus quidem. Ea libero ipsum pariatur quisquam mollitia vel.', '2018-03-26', 'images/fake-image.jpg', 'Maria Armstrong'),
(87, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Unde omnis non id.', 'Tempore fugiat est porro vitae est hic quidem. Molestiae eos consectetur nisi debitis autem eveniet assumenda. In aliquam ut voluptatem tenetur vero.\n\nQui fugiat debitis iusto odit. Aut perferendis commodi ad dolorum non. Aspernatur voluptatem sint dignissimos ipsam.\n\nIn rerum qui dignissimos modi. Ut unde expedita eos laboriosam sit. Explicabo mollitia nisi cumque est est. Quibusdam ipsam quasi quisquam.', '1994-03-01', 'images/fake-image.jpg', 'Reva Fisher MD'),
(88, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Voluptate id voluptatibus in omnis.', 'Assumenda facere eaque non porro sunt. Porro laboriosam distinctio sed quia. Harum fuga fugiat beatae earum facilis. Recusandae aut doloremque ut nihil at.\n\nNecessitatibus voluptas laborum incidunt quisquam. Corrupti veniam laborum harum. Quo vero modi commodi provident laudantium repellendus.\n\nPossimus accusamus quia veritatis pariatur optio placeat. Aut qui vel autem enim harum rem vitae et. Repellendus aut aut molestias quo laborum et.', '2002-06-11', 'images/fake-image.jpg', 'Eleazar Trantow V'),
(89, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Explicabo accusamus asperiores illo omnis quia id.', 'Eum unde maiores voluptatem dolores quo quae. Sint at dicta laudantium illo.\n\nRem perferendis voluptatem optio ducimus. Eaque sapiente optio magni totam. Quis et nostrum architecto numquam.\n\nHic corrupti sed esse cumque est dolore. Sit quia explicabo expedita. Officiis maxime praesentium amet placeat qui qui natus.', '2001-12-14', 'images/fake-image.jpg', 'Judson Klein'),
(90, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Qui recusandae inventore eaque molestiae laboriosam.', 'Amet natus dignissimos est. Est aspernatur corrupti aliquam culpa laboriosam. Ad dolore ut quia harum vel minus dolorem. Iure expedita veritatis eum illum omnis nihil.\n\nItaque ab dolor delectus in recusandae sed et. Earum quidem iste a eveniet dolor sed. Ut quos recusandae autem omnis. Ea officiis voluptatem in nam iste. Repellendus neque distinctio distinctio.\n\nNam aliquam est repellat et rem. Labore est soluta mollitia tenetur voluptatem. Laboriosam ut aspernatur dolorem unde tenetur itaque. Aspernatur deleniti voluptatibus autem aut nihil id iste sed.', '1991-06-23', 'images/fake-image.jpg', 'Hollis Adams'),
(91, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Laboriosam aliquid veritatis animi illum quia et sed.', 'Rerum voluptates debitis tenetur eos ut similique repellendus. Blanditiis quia nisi dolor ut. Enim doloribus est dolorem tempore repellat. Atque perspiciatis porro nostrum corporis ducimus eveniet optio aliquid.\n\nIn quo laboriosam laudantium consequuntur. Odio mollitia minima expedita quasi et alias. Molestiae mollitia ut et iusto illum alias quisquam a. Alias reprehenderit et vero sunt.\n\nTempora ut nobis voluptatem aperiam illo qui dolor. Et ratione itaque itaque in alias aliquid. Nihil reiciendis autem aut consequatur a excepturi. Ut facilis nobis qui dicta.', '1992-03-13', 'images/fake-image.jpg', 'Prof. Daron Upton'),
(92, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Velit et animi occaecati alias qui aut.', 'Rem vel quia praesentium tenetur neque. Laborum ad et corporis aliquam. Aut maiores dolorem veritatis itaque molestiae voluptatem possimus.\n\nOmnis non non magnam ut cupiditate. Sed exercitationem perspiciatis explicabo consequatur nihil. Corporis necessitatibus qui magni delectus sunt mollitia earum corporis. Et maiores iusto nihil qui et sit aliquid nihil. Eius possimus sequi consequatur quia est recusandae qui.\n\nAutem perspiciatis sit voluptate recusandae sint voluptas. Nostrum hic tenetur quas et non qui et. Aperiam sit aut id.', '1979-02-18', 'images/fake-image.jpg', 'Hettie Mohr'),
(93, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Distinctio facere perspiciatis ullam sit hic id.', 'Maiores provident illo repellendus et autem reprehenderit at. Magni nobis numquam impedit vel. Dolor ut omnis rem sequi quibusdam.\n\nCum aperiam quia mollitia dolores. Tempore quo autem ducimus sit repellendus voluptatem.\n\nCupiditate non et unde eum debitis ut. Quos et sit tempora. Sit a consectetur vel quod. Aut molestiae totam minus doloremque velit.', '2020-07-17', 'images/fake-image.jpg', 'Ernestina Treutel'),
(94, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Quos laborum magni qui alias rerum.', 'Architecto exercitationem distinctio qui excepturi sunt. Suscipit sed architecto id quas veritatis. Repudiandae provident excepturi natus tempora recusandae. Libero quos et odio quod autem quia libero.\n\nAut assumenda est nisi excepturi minima aut. Neque aut hic voluptatum rerum molestiae.\n\nEum sequi rerum qui commodi dicta. Eveniet voluptatem fuga laudantium ut. Eum quibusdam deserunt quisquam enim est. Corrupti praesentium id voluptatem hic quis molestiae.', '1978-04-05', 'images/fake-image.jpg', 'Shakira Eichmann'),
(95, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolorem qui eius porro quod exercitationem omnis.', 'Odit quis incidunt numquam rerum illum explicabo voluptatem. Qui laborum commodi sit recusandae. Maxime id quod a.\n\nAut facere doloribus aut ullam nihil distinctio eligendi aut. Cupiditate autem dolore explicabo qui quaerat. Modi consectetur velit quod. Debitis qui blanditiis sed expedita.\n\nEaque ut veritatis similique cum. Est quaerat quaerat sit quos quia eligendi iusto. Et velit labore repellendus voluptatum praesentium quas. Et enim voluptatem nobis.', '2011-07-06', 'images/fake-image.jpg', 'Sabryna Zulauf'),
(96, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Dolorem non eos ex iusto sit qui.', 'Ut quos quisquam sed et. Facere eius autem velit quis officia aut rem. Tenetur accusamus harum beatae deserunt eaque amet quis tenetur.\n\nVoluptatibus qui natus enim aut quae autem aut. Blanditiis omnis laudantium quos quis. Sunt et id omnis velit laborum quod consequatur. Accusantium et cupiditate atque aliquid dolore.\n\nQui possimus dolorem occaecati laborum dignissimos iste nobis non. Ut harum alias iure voluptatibus dolorum. Est quidem eius doloribus molestiae omnis consequatur nihil molestiae. Commodi sed non officiis ipsam eos.', '2001-05-15', 'images/fake-image.jpg', 'Mikel Collier'),
(97, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Reiciendis porro eos accusamus ducimus suscipit sapiente placeat.', 'Aut nobis qui facere sint sunt. Sunt debitis est harum fugit.\n\nFugiat voluptates eius occaecati ipsum dignissimos. Nulla sed est fugit sed optio et optio. Qui incidunt voluptatem quasi excepturi rerum ut.\n\nNostrum rerum consectetur sint velit aut. Est libero occaecati sunt quis. Ad molestias molestias vel molestiae nesciunt voluptas ut. Consequuntur omnis repellendus eum. Nobis illo et maxime doloremque.', '1972-08-29', 'images/fake-image.jpg', 'Prof. Marietta Kunze Jr.'),
(98, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Omnis quod voluptas vel tempore accusantium.', 'Eos omnis reiciendis dolores modi. Voluptates architecto beatae molestias totam dolore dolorem ea. Iure recusandae voluptates neque quasi. Corrupti sit deserunt illo qui.\n\nAsperiores deleniti ut est voluptatem amet. Non accusamus molestiae et rerum quos porro. Consequatur exercitationem voluptatem consequatur magni ut sint qui ex. Et ullam et sit ipsum dolore itaque dolore. Suscipit consequatur asperiores animi est provident perferendis quidem.\n\nFacilis et est ipsa qui. Sed similique earum labore enim suscipit deserunt qui. Est ut qui esse doloremque est.', '2015-10-01', 'images/fake-image.jpg', 'Jaime Treutel Sr.'),
(99, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Optio quibusdam temporibus ratione excepturi ad.', 'Voluptatem dolorum in dignissimos enim. Dolorem similique fugiat voluptas hic explicabo veniam earum. Quia ullam quia ipsum sunt omnis autem et.\n\nVoluptas nesciunt ipsum odit provident est. Dolorem laudantium nisi vero est optio. Aut aut enim voluptas deleniti. Accusantium qui aliquam modi voluptas enim.\n\nRerum nemo quia et id porro eaque est. In labore officia pariatur corporis repellendus. Tenetur adipisci vitae voluptatibus cum voluptatem optio ut.', '1981-03-26', 'images/fake-image.jpg', 'Tiara Greenfelder'),
(100, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Tempore modi eius deserunt.', 'Amet sunt suscipit aut porro. Iure atque eos rerum aut id unde. Recusandae quidem in dignissimos magni possimus. Quia amet nostrum quia aperiam ipsum ea quos.\n\nNon deserunt aliquam eos quia. Omnis repudiandae quis harum vel impedit. Et ex ut dicta eveniet.\n\nEst velit perspiciatis dignissimos dolores ullam eum enim. Excepturi aliquid officia et quia. Repudiandae molestiae consequatur modi ab totam consectetur aspernatur. Unde ipsa itaque unde provident sint quis molestiae. Laudantium reprehenderit voluptatem consequatur facilis nesciunt sunt.', '2004-10-11', 'images/fake-image.jpg', 'Helen Howell II'),
(101, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Temporibus modi harum expedita non.', 'Ea repellendus repellendus est dicta magni sint ipsum. Atque quas et eius ex quo dolorum aut. Et aut laudantium quis voluptatem quis. Vel dolorum vel consequatur libero.\n\nMollitia et rerum dicta suscipit ut qui consectetur nemo. Voluptatem praesentium totam et sunt beatae rerum. Nihil et nemo et quaerat aut sed.\n\nOfficia molestiae omnis necessitatibus officiis nostrum. Consequuntur exercitationem quas quos nihil. Libero esse aut et quaerat eos accusantium. Voluptas necessitatibus vitae qui.', '2007-10-12', 'images/fake-image.jpg', 'Janie Ondricka'),
(102, '2023-06-22 20:32:50', '2023-06-22 20:32:50', 'Illo qui et sequi asperiores similique tempore id fuga.', 'Ut quidem consequuntur quasi deserunt est. Nisi eos omnis ut ipsa et voluptatem. Omnis iure autem occaecati ut et porro rerum. Nihil aliquid animi culpa quam in maiores. Non error facere corporis quos odio.\n\nHic soluta omnis nisi est voluptatem illum. Laudantium nihil aperiam incidunt quis. Non iure asperiores blanditiis ullam autem sit ipsum enim.\n\nNulla rerum qui doloremque placeat non magnam vel. Ut quam sed dolor distinctio nisi. Nam aut nam voluptatem sunt ut molestias.', '1995-09-21', 'images/fake-image.jpg', 'Ramon Blanda V');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `password_reset_tokens`
--

CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `token` varchar(64) NOT NULL,
  `abilities` text DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(2, 'sforjab', 'sforjab@uoc.edu', NULL, '$2y$10$FjfMg0gIfn2RyD24/.ch.O2sS.pR14oUaBnd21bd1Soc67DESs8Ne', NULL, '2023-06-21 09:39:47', '2023-06-21 09:39:47');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indices de la tabla `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `noticias`
--
ALTER TABLE `noticias`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `password_reset_tokens`
--
ALTER TABLE `password_reset_tokens`
  ADD PRIMARY KEY (`email`);

--
-- Indices de la tabla `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indices de la tabla `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT de la tabla `noticias`
--
ALTER TABLE `noticias`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=104;

--
-- AUTO_INCREMENT de la tabla `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
